# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16k9SbiY6-xzZANSPf8xfL018FVKN9jQ9

# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

**Objectives:**

*   List popular languages for Data Science.
*   List  commonly used libraries used by Data Scientists.
*   Discussed examples of evaluating arithmetic expressions in Python.

Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL
4. Julia
5. Scala

Some of the commonly used libraries used by Data Scientists include:
1. NumPy
2. Pandas
3. Matplotlib
4. Seaborn
5. Scikiy-learn

| Data Science Tools |
|---|
| Jupyter Notebook |
| Apache Spark |
| Spyder |

###Below are a few examples of evaluating arithmetic expressions in Python

This a simple arithmetic expression to mutiply then add integers
"""

(3*4)+5

"""This will convert 200 minutes to hours by diving by 60"""

200/60

"""##Author

Emerald Hettiarachchi
"""